version: '3'
services:

  php8site:
    image: php8
    container_name: php8salbarche
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"

  db:
    image: mariadb:10.4
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
